export { default as CommentParser } from './CommentParser'
export { default as parseComment } from './parseComment'
export { default as patterns } from './patterns'
export { default as checkFile } from './check/checkFile'
export { default as checkFiles } from './check/checkFiles'
